### ISSUE TITLE
handle reboot

### ISSUE THREAD

**Issue by rhmk** [linux-system-roles/sap-hana-preconfigure#103]
The default behaviour of the role is, that it fails, if reboot is required after package install. I can also set to ignore it. with setting the rolle is currently not able to handle a proper install fully automatically including the reboot.
I add like to add option instead of failing if reboot is required, to just reboot. If reboot is wanted, set a timeout to do the reboot.

**Comment by richm** [comment]
We do something similar in the kernel_settings role - https://github.com/linux-system-roles/kernel_settings#role-variables - see `kernel_settings_reboot_ok` and `kernel_settings_reboot_required`

**Comment by tbludau** [comment]
This role is for the preparation of a new system (that is while we named it preconfigure). So the reboot feature is fine while preparing the system for the first time.

When rerunning the playbook (idempotent) while updated some packages the systems could also be rebooted. 

In customer enviornments it could be a huge problem when the running a SAP HANA Database and the system will be rebooted in the middle of the business. (That's because SAP HANA is not a DevOps Tool..)

Even if we appeal to the common sense of the administrators, this case will happen at some point. That would be directly traced back to this playbook.

Could it be a good idea to configure a manual commando on the system directly to force the reboot mechanism? (f.e. set a fact to allow one reboot) so the administrator exactly knows what he is doing?

My Idea:
First Run: 
- Check Fact if system should be rebooted
- Set fact, that initial Reboot was initiated / interrupted
- Reboot System is configured

Second (following) Runs
- Check Fact if system should be rebooted
- no only give a warning or perhaps a fail


My second Idea:
We only inform that the system should be rebootet with to parameter definitions:
- Failed on necessary reboot (Standard, so the user has to interact, and configure one parameter, to skip this fail, then he knows what had to be done)
- Warning on necessary reboot (After setting a parameter)

**Comment by berndfinger** [comment]
I am going to implement the following in case a reboot is required:
1) The role can reboot the managed node(s)
2) The role can fail at the end of the run
3) The role can print a warning message at the end of the run
Same for role sap-preconfigure, see https://github.com/linux-system-roles/sap-preconfigure/issues/108 .

**Comment by berndfinger** [comment]
The behavior is determined by the following variables:
sap_hana_preconfigure_reboot_ok: (default: no)
sap_hana_preconfigure_fail_if_reboot_required: (default: yes)
If sap_hana_preconfigure_reboot_ok is set to yes, it will reboot the node (if required) no matter how sap_hana_preconfigure_fail_if_reboot_required is set.
