### ISSUE TITLE
Store customized parameters which survive an update of the roles package.

### ISSUE THREAD

**Issue by berndfinger** [linux-system-roles/sap-hana-preconfigure#122]

**Comment by pcahyna** [comment]
I don't understand. Why don't customized parameters survive an update of the roles package? What parameters do you have in mind?

**Comment by berndfinger** [comment]
I want customers to be able to - for example - change net.ipv4.tcp_timestamps to 0. This parameter is set to 1 in vars/RedHat_8.yml and we do not plan to change it. But for some customers, it might be desirable to set it to 0.

**Comment by pcahyna** [comment]
If this parameter is intended to be changeable, it should be moved to defaults from vars. Even if it is not moved, there are ways to override role vars from user playbooks (https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable, any method listed under item 15 should work).

**Comment by rhmk** [comment]
The old role has it in default. Those kernel parameters need to be configurable, so that the role can be re-run to set/Check these parameters after re-run. IIRC - the required minimal setting is defined in /var and that in defaults/the variable that is actually used is defined and hence can be overwritten. In a production environment the variables should be stored in a hosts file, so that tehy always will be reapplied.

**Comment by berndfinger** [comment]
As there are various ways to store user configurable parameters which are independent of the roles code, I am closing this issue.
Thanks for your feedback!
