### ISSUE TITLE
template error while templating string

### ISSUE THREAD

**Issue by poonjolaig** [linux-system-roles/sap-hana-preconfigure#127]
Getting below fatal message.

TASK [sap-hana-preconfigure : debug] ********************************************************************************************************************************************************************************************************
ok: [hana-vm1] => {
    "reqpkgs": [
        [
            "kernel",
            "3.10.0-957.1.3.el7"
        ]
    ]
}

TASK [sap-hana-preconfigure : set_fact] *****************************************************************************************************************************************************************************************************
fatal: [hana]: FAILED! => {"msg": "template error while templating string: expected token '=', got '.'. String: {% set ns = namespace() %}\n{% set ns.pkgs = [] %}\n{% for reqpkg in reqpkgs %}\n{%   if not reqpkg[0] in ansible_facts.packages %}\n{%     set _ = ns.pkgs.append(reqpkg | join('-')) %}\n{%   else %}\n{%     set pkg = ansible_facts.packages[reqpkg[0]][-1] %}\n{%     set verrel = pkg.version ~ '-' ~ pkg.release %}\n{%     if reqpkg[1].replace (\".el\", \".0.0.\") is version(verrel.replace (\".el\", \".0.0.\"), '>', strict=false) %}\n{%       set _ = ns.pkgs.append(reqpkg | join('-')) %}\n{%     else %}\n{%       set _ = \"pkg already installed with same or later version\" %}\n{%     endif %}\n{%   endif %}\n{% endfor %}\n{{ ns.pkgs }}"}

**Comment by berndfinger** [comment]
This issue is known to occur in case the control node has package python3-jinja2 before version 2.10, for example when running this version of sap-hana-preconfigure on RHEL 7. See also https://github.com/linux-system-roles/sap-hana-preconfigure/issues/117 .
A workaround on pre-RHEL 8 control nodes would be to run the role with variable sap_hana_preconfigure_min_package_check set to "no" and install the correct versions of the packages __sap_hana_preconfigure_min_packages in a separate step.
